import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { cn } from "@/shadcn/utils";
import { Toolbar } from "@/components/layout/toolbar";
import { Footer } from "@/components/layout/footer";

import "@/style/global.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={cn(inter.className, 'flex-col-sbc min-h-screen xl:h-screen')}
      >
        <Toolbar />
        <div className='LAYOUT_INNER overflow-y-scroll xl:h-full w-[var(--layout-width)] flex-tl border-r border-l border-neutral-800'>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
